[package]
name = "sdecode-preimages"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/sdecode-preimages"
description = "Keccak256 preimages."
license.workspace = true
keywords.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
sdecode-preimages-interface.workspace = true

alloy-primitives.workspace = true

serde = { workspace = true, optional = true }
hashbrown.workspace = true

quick-impl.workspace = true
overf.workspace = true

[dev-dependencies]
alloy-primitives = { workspace = true, features = ["rand"] }

[features]
serde = [
    "sdecode-preimages-interface/serde",
    "dep:serde",
    "serde/derive",
    "alloy-primitives/serde",
    "hashbrown/serde",
]
