[package]
name = "sdecode"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/sdecode"
description = "Decode any EVM storage."
license.workspace = true
keywords.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
sdecode-preimages.workspace = true
sdecode-core.workspace = true
sdecode-solidity.workspace = true
sdecode-solidity-macro.workspace = true

[dev-dependencies]
sdecode-solidity = { workspace = true, features = ["hashbrown"] }
sdecode-test-utils.workspace = true

alloy-primitives.workspace = true
hashbrown.workspace = true

serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[features]
serde = [
    "sdecode-preimages/serde",
    "sdecode-core/serde"
]
indexmap = ["sdecode-solidity/indexmap"]
hashbrown = ["sdecode-solidity/hashbrown"]
