[package]
name = "sdecode-core"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/sdecode-core"
license.workspace = true
keywords.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
sdecode-preimages.workspace = true
alloy-primitives.workspace = true
auto_impl.workspace = true
serde = { workspace = true, features = ["derive"], optional = true }
quick-impl.workspace = true
thiserror.workspace = true
overf.workspace = true

[features]
serde = ["dep:serde", "alloy-primitives/serde"]
