[package]
name = "sdecode-test-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/sdecode-test-utils"
license.workspace = true
keywords.workspace = true

[dependencies]
sdecode = { workspace = true, features = ["serde"] }

alloy-primitives.workspace = true
alloy-preimages.workspace = true

serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
