[package]
name = "sdecode-cli"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Decode any EVM storage."
license.workspace = true
keywords.workspace = true

[dependencies]
sdecode.workspace = true
