[package]
name = "sdecode-inspector"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/sdecode-inspector"
license.workspace = true
keywords.workspace = true

[dependencies]
alloy-preimages.workspace = true
alloy-primitives.workspace = true

revm-inspector.workspace = true
revm-interpreter.workspace = true
revm-bytecode.workspace = true

overf.workspace = true
quick-impl.workspace = true

[dev-dependencies]
revm.workspace = true
